apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-termination-handler-spot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"    
spec:
  project: default
  destination:
    name: spot-friendly-cluster
    namespace: kube-system
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-node-termination-handler
    targetRevision: 0.21.0
    helm:
      values: |
        enableSpotInterruptionDraining: true
        enableScheduledEventDraining: true
        enableRebalanceMonitoring: true
        enableRebalanceDraining: true
        awsRegion: ap-northeast-2
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true