apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: thanos
    targetRevision: 15.13.2
    helm:
      skipCrds: true
      values: |
        existingObjstoreSecret: thanos-objstore-secret

        receive:
          enabled: true
          tsdbRetention: 6h
          persistence:
            enabled: false
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 1Gi

        storegateway:
          enabled: true
          persistence:
            enabled: false

        query:
          enabled: true

        metrics:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true