fullnameOverride: prometheus

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    retention: 6h
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path        
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 6h  # flush 테스트를 위한 짧은 리텐션 설정 (테스트 후 늘릴 수 있음)
    walCompression: true
    enableAdminAPI: true  # flush 강제 종료 실험 등에 필요
    remoteWrite:
      - url: "http://thanos-receive.monitoring.svc.cluster.local:19291/api/v1/receive"

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path        
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

  service:
    type: ClusterIP
    port: 9090
    annotations:
      prometheus.io/scrape: "true"

grafana:
  enabled: true
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true