apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-addon 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/J1kr/spot-friendly-gitops
    targetRevision: HEAD
    path: addon/mgmt-local-cluster
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true