frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: dmogki/frontend
    tag: v0.1.0
  nodeSelector: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  pdb:
    enabled: false
    minAvailable: 1

adservice:
  enabled: true
  replicaCount: 2
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
    tag: v0.10.2
  nodeSelector: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  pdb:
    enabled: false
    minAvailable: 1

checkoutservice:
  enabled: true
  replicaCount: 2
  image:
    repository: dmogki/checkoutservice
    tag: v0.1.0
  nodeSelector: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: false
    minAvailable: 1

emailservice:
  enabled: true
  replicaCount: 2
  image:
    repository: dmogki/emailservice
    tag: v0.1.1
  nodeSelector: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  pdb:
    enabled: false
    minAvailable: 1

paymentservice:
  enabled: true
  replicaCount: 2
  image:
    repository: dmogki/paymentservice
    tag: v0.1.0
  nodeSelector: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  pdb:
    enabled: false
    minAvailable: 1

recommendationservice:
  enabled: true
  image:
    repository: dmogki/recommendationservice
    tag: v0.1.1
  replicaCount: 2
  nodeSelector: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: false
    minAvailable: 1


cartservice:
  enabled: true
  replicaCount: 2
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
    tag: v0.10.2
  nodeSelector: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: false
    minAvailable: 1

currencyservice:
  enabled: true
  replicaCount: 2
  image:
    repository: dmogki/currencyservice
    tag: v0.1.0
  nodeSelector: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: false
    minAvailable: 1

productcatalogservice:
  enabled: true
  replicaCount: 2
  image:
    repository: dmogki/productcatalogservice
    tag: v0.1.0
  nodeSelector: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: false
    minAvailable: 1

shippingservice:
  enabled: true
  replicaCount: 2
  image:
    repository: dmogki/shippingservice
    tag: v0.1.0
  nodeSelector: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: false
    minAvailable: 1

loadgenerator:
  enabled: true
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator
    tag: v0.10.2
  replicaCount: 0
  env:
    users: "100"
    rate: "10"
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  

rediscart:
  pdb:
    enabled: false
    minAvailable: 1

istio:
  host: boutique.mogki.com  