frontend:
  enabled: true
  replicaCount: 3
  image:
    repository: dmogki/frontend
    tag: v0.1.1
  nodeSelector:
    node-role: spot
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - frontend
          topologyKey: "kubernetes.io/hostname"
  tolerations: []
  topologySpreadConstraints: []
  pdb:
    enabled: true
    minAvailable: 1

adservice:
  enabled: true
  replicaCount: 3
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
    tag: v0.10.2
  nodeSelector:
    node-role: spot
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - adservice
          topologyKey: "kubernetes.io/hostname"
  tolerations: []
  topologySpreadConstraints: []
  pdb:
    enabled: true
    minAvailable: 1

checkoutservice:
  enabled: true
  replicaCount: 3
  image:
    repository: dmogki/checkoutservice
    tag: v0.1.1
  nodeSelector:
    node-role: spot
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - checkoutservice
          topologyKey: "kubernetes.io/hostname"
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: true
    minAvailable: 1

emailservice:
  enabled: true
  replicaCount: 3
  image:
    repository: dmogki/emailservice
    tag: v0.1.1
  nodeSelector:
    node-role: spot
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - emailservice
          topologyKey: "kubernetes.io/hostname"
  tolerations: []
  topologySpreadConstraints: []
  pdb:
    enabled: true
    minAvailable: 1

paymentservice:
  enabled: true
  replicaCount: 3
  image:
    repository: dmogki/paymentservice
    tag: v0.1.0
  nodeSelector:
    node-role: spot
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - paymentservice
          topologyKey: "kubernetes.io/hostname"
  tolerations: []
  topologySpreadConstraints: []
  pdb:
    enabled: true
    minAvailable: 1

recommendationservice:
  enabled: true
  image:
    repository: dmogki/recommendationservice
    tag: v0.1.1
  replicaCount: 3
  nodeSelector:
    node-role: spot
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - recommendationservice
          topologyKey: "kubernetes.io/hostname"
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: true
    minAvailable: 1


cartservice:
  enabled: true
  replicaCount: 3
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
    tag: v0.10.2
  nodeSelector:
    node-role: spot
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - cartservice
          topologyKey: "kubernetes.io/hostname"
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: true
    minAvailable: 1

currencyservice:
  enabled: true
  replicaCount: 3
  image:
    repository: dmogki/currencyservice
    tag: v0.1.0
  nodeSelector:
    node-role: spot
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - currencyservice
          topologyKey: "kubernetes.io/hostname"
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: true
    minAvailable: 1

productcatalogservice:
  enabled: true
  replicaCount: 3
  image:
    repository: dmogki/productcatalogservice
    tag: v0.1.0
  nodeSelector:
    node-role: spot
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - productcatalogservice
          topologyKey: "kubernetes.io/hostname"
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: true
    minAvailable: 1

shippingservice:
  enabled: true
  replicaCount: 3
  image:
    repository: dmogki/shippingservice
    tag: v0.1.0
  nodeSelector:
    node-role: spot
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - shippingservice
          topologyKey: "kubernetes.io/hostname"
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: true
    minAvailable: 1

loadgenerator:
  enabled: true
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator
    tag: v0.10.2
  replicaCount: 0
  env:
    users: "2000"
    rate: "100"
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  nodeSelector:
    node-role: managed
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  

rediscart:
  pdb:
    enabled: false
    minAvailable: 1

istio:
  host: boutique.mogki.com  
