frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
    tag: v0.10.2
  nodeSelector:
    node-role: spot
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  pdb:
    enabled: true
    minAvailable: 1
 
adservice:
  enabled: true
  replicaCount: 2
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
    tag: v0.10.2
  nodeSelector:
    node-role: spot
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  pdb:
    enabled: true
    minAvailable: 1

checkoutservice:
  enabled: true
  replicaCount: 2
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
    tag: v0.10.2
  nodeSelector:
    node-role: spot
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: true
    minAvailable: 1

emailservice:
  enabled: true
  replicaCount: 2
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
    tag: v0.10.2
  nodeSelector:
    node-role: spot
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  pdb:
    enabled: true
    minAvailable: 1

paymentservice:
  enabled: true
  replicaCount: 2
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
    tag: v0.10.2
  nodeSelector:
    node-role: spot
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  pdb:
    enabled: true
    minAvailable: 1

recommendationservice:
  enabled: true
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
    tag: v0.10.2
  replicaCount: 2
  nodeSelector:
    node-role: spot
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: true
    minAvailable: 1


cartservice:
  enabled: true
  replicaCount: 2
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
    tag: v0.10.2
  nodeSelector:
    node-role: spot
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: true
    minAvailable: 1

currencyservice:
  enabled: true
  replicaCount: 2
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice
    tag: v0.10.2
  nodeSelector:
    node-role: spot
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: true
    minAvailable: 1

productcatalogservice:
  enabled: true
  replicaCount: 2
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice
    tag: v0.10.2
  nodeSelector:
    node-role: spot
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: true
    minAvailable: 1

shippingservice:
  enabled: true
  replicaCount: 2
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice
    tag: v0.10.2
  nodeSelector:
    node-role: spot
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  
  pdb:
    enabled: true
    minAvailable: 1

loadgenerator:
  enabled: true
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator
    tag: v0.10.2
  replicaCount: 0
  env:
    users: "50"
    rate: "10"
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  nodeSelector:
    node-role: managed
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []  

rediscart:
  pdb:
    enabled: true
    minAvailable: 1

istio:
  host: boutique.mogki.com  