apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-certificate
  namespace: argocd
spec:
  project: default
  destination:
    name: spot-friendly
    namespace: kube-system
  source:
    repoURL: https://charts.helm.sh/incubator
    targetRevision: "0.2.5"
    chart: raw
    helm:
      values: |-
        resources:
          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: letsencrypt-dns-irsa
            spec:
              acme:
                email: mogki@naver.com
                server: https://acme-v02.api.letsencrypt.org/directory
                privateKeySecretRef:
                  name: letsencrypt-dns-irsa-key
                solvers:
                  - dns01:
                      route53:
                        region: ap-northeast-2
                    
          - apiVersion: cert-manager.io/v1
            kind: Certificate
            metadata:
              name: wildcard-mogki-com
              namespace: istio-system
            spec:
              secretName: wildcard-mogki-com-tls
              issuerRef:
                name: letsencrypt-dns-irsa
                kind: ClusterIssuer
              commonName: mogki.com
              dnsNames:
                - mogki.com
                - '*.mogki.com'                   
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true