apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector-spot
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.120.0
    helm:
      values: |
        image:
          repository: otel/opentelemetry-collector-contrib
          tag: 0.120.0

        mode: deployment

        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
          exporters:
            otlp:
              endpoint: tempo.tracing.svc.cluster.local:4317
              tls:
                insecure: true

          service:
            pipelines:
              traces:
                receivers: [otlp]
                exporters: [otlp]

        service:
          enabled: true
          type: ClusterIP

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true