{{- if .Values.adservice.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  replicas: {{ .Values.adservice.replicaCount }}
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: adservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: {{ .Values.adservice.image.repository | default "us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice" }}:{{ .Values.adservice.image.tag | default "v0.10.2" }}
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 9555
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 9555
      nodeSelector:
        {{- toYaml .Values.adservice.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.adservice.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.adservice.tolerations | nindent 8 }}
      topologySpreadConstraints:
        {{- toYaml .Values.adservice.topologySpreadConstraints | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
{{- if .Values.adservice.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: adservice-pdb
spec:
  minAvailable: {{ .Values.adservice.pdb.minAvailable }}
  selector:
    matchLabels:
      app: adservice
{{- end }}
{{- end }}
