{{- if .Values.checkoutservice.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
  replicas: {{ .Values.checkoutservice.replicaCount }}
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      serviceAccountName: checkoutservice
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: {{ .Values.checkoutservice.image.repository }}:{{ .Values.checkoutservice.image.tag }}
          ports:
            - containerPort: 5050
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 2             
            timeoutSeconds: 1            
            failureThreshold: 2          
            successThreshold: 1           
            grpc:
              port: 5050
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 2             
            timeoutSeconds: 1            
            failureThreshold: 2          
            successThreshold: 1           
            grpc:
              port: 5050
          env:
            - name: PORT
              value: "5050"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
            - name: PAYMENT_SERVICE_ADDR
              value: "paymentservice:50051"
            - name: EMAIL_SERVICE_ADDR
              value: "emailservice:5000"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: ENABLE_TRACING
              value: "1"
            - name: COLLECTOR_SERVICE_ADDR
              value: "otel-collector-spot-opentelemetry-collector.tracing.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "checkoutservice"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      nodeSelector: {{- toYaml .Values.checkoutservice.nodeSelector | nindent 8 }}
      affinity: {{- toYaml .Values.checkoutservice.affinity | nindent 8 }}
      tolerations: {{- toYaml .Values.checkoutservice.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.checkoutservice.topologySpreadConstraints | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
    - name: grpc
      port: 5050
      targetPort: 5050
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice
{{- if .Values.checkoutservice.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: checkoutservice-pdb
spec:
  minAvailable: {{ .Values.checkoutservice.pdb.minAvailable }}
  selector:
    matchLabels:
      app: checkoutservice
{{- end }}
{{- end }}