{{- if .Values.paymentservice.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: {{ .Values.paymentservice.replicaCount }}
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      serviceAccountName: paymentservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "{{ .Values.paymentservice.image.repository | default "dmogki/paymentservice" }}:{{ .Values.paymentservice.image.tag | default "v0.0.3" }}"
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        - name: ENABLE_TRACING
          value: "1"
        - name: COLLECTOR_SERVICE_ADDR
          value: "otel-collector-opentelemetry-collector.tracing.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "paymentservice"
        readinessProbe:
          grpc:
            port: 50051
        livenessProbe:
          grpc:
            port: 50051
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      nodeSelector: {{- toYaml .Values.paymentservice.nodeSelector | nindent 8 }}
      affinity: {{- toYaml .Values.paymentservice.affinity | nindent 8 }}
      tolerations: {{- toYaml .Values.paymentservice.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.paymentservice.topologySpreadConstraints | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice
{{- if .Values.paymentservice.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: paymentservice-pdb
spec:
  minAvailable: {{ .Values.paymentservice.pdb.minAvailable }}
  selector:
    matchLabels:
      app: paymentservice
{{- end }}
{{- end }}