apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-node-spot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"    
spec:
  project: default
  destination:
    name: spot-friendly-cluster
    namespace: karpenter
  source:
    repoURL: https://charts.helm.sh/incubator
    targetRevision: "0.2.5"
    chart: raw
    helm:
      values: |-
        resources:
          - apiVersion: karpenter.k8s.aws/v1
            kind: EC2NodeClass
            metadata:
              name: default
            spec:
              amiFamily: AL2
              role: arn:aws:iam::105847046109:instance-profile/KarpenterNodeInstanceProfile-spot-friendly-cluster
              subnetSelectorTerms:
                - tags:
                    "karpenter.sh/discovery": spot-friendly-cluster
              securityGroupSelectorTerms:
                - tags:
                    "karpenter.sh/discovery": spot-friendly-cluster

          - apiVersion: karpenter.sh/v1
            kind: NodePool
            metadata:
              name: spot
            spec:
              template:
                metadata:
                  labels:
                    node.karpenter.sh/lifecycle: spot
                spec:
                  nodeClassRef:
                    name: default
                  requirements:
                    - key: "karpenter.k8s.aws/instance-cpu"
                      operator: In
                      values: ["4"]
                    - key: "karpenter.k8s.aws/instance-memory"
                      operator: In
                      values: ["16384"]
                    - key: "karpenter.k8s.aws/capacity-type"
                      operator: In
                      values: ["spot"]
                    - key: "karpenter.k8s.aws/instance-hypervisor"
                      operator: In
                      values: ["nitro"]
                    - key: "karpenter.k8s.aws/instance-category"
                      operator: In
                      values: ["t", "m"]
              limits:
                resources:
                  cpu: 64
                  memory: 256Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 24h
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
