apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-spot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  destination:
    name: spot-friendly-cluster
    namespace: kube-system
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: 1.4.0
    helm:
      values: |
        controller:
          serviceAccount:
            create: false
            name: karpenter
        settings:
          clusterName: spot-friendly-cluster
          interruptionQueue: spot-friendly-cluster
          aws:
            defaultInstanceProfile: KarpenterNodeInstanceProfile-spot-friendly-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true