apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-nodepool
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"    
spec:
  project: default
  destination:
    name: spot-friendly-cluster
    namespace: karpenter
  source:
    repoURL: https://charts.helm.sh/incubator
    targetRevision: "0.2.5"
    chart: raw
    helm:
      values: |-
        resources:
          - apiVersion: karpenter.sh/v1
            kind: NodePool
            metadata:
              name: spot
            spec:
              template:
                spec:
                  nodeClassRef:
                    name: default
                    kind: EC2NodeClass
                    group: karpenter.k8s.aws
                  requirements:
                    - key: karpenter.sh/capacity-type
                      operator: In
                      values: ["spot"]
                    - key: kubernetes.io/arch
                      operator: In
                      values: ["amd64"]
                    - key: kubernetes.io/os
                      operator: In
                      values: ["linux"]
                    - key: karpenter.k8s.aws/instance-category
                      operator: In
                      values: ["t", "m"]
                    - key: karpenter.k8s.aws/instance-cpu
                      operator: In
                      values: ["4"]
                    - key: "topology.kubernetes.io/zone"
                      operator: In
                      values: ["ap-northeast-2a", "ap-northeast-2c"]          
                    - key: karpenter.k8s.aws/instance-memory
                      operator: In
                      values: ["16384"]
                    - key: karpenter.k8s.aws/instance-hypervisor
                      operator: In
                      values: ["nitro"]
              limits:
                cpu: 64
                memory: "256Gi"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
