apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base-spot
  namespace: argocd
  annotations:  
   argocd.argoproj.io/sync-wave: "0"  
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: 1.25.0
  destination:
    name: spot-friendly
    namespace: istio-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true