apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-spot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
spec:
  project: default
  destination:
    name: spot-friendly-cluster
    namespace: logging
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      skipCrds: true
      values: |
        loki:
          enabled: true

          persistence:
            enabled: false

          storage:
            type: "s3"

          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-s3-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-s3-secret
                  key: AWS_SECRET_ACCESS_KEY
          config:
            schema_config:
              configs:
                - from: 2024-01-01
                  store: boltdb-shipper
                  object_store: s3
                  schema: v11
                  index:
                    prefix: loki_index_spot
                    period: 24h
            storage_config:
              aws:
                bucketnames: j1-lab-loki
                endpoint: s3.ap-northeast-2.amazonaws.com
                region: ap-northeast-2
                insecure: false
                s3forcepathstyle: true
              boltdb_shipper:
                shared_store: s3
                cache_ttl: 24h

        promtail:
          enabled: true
          config:
            clients:
              - url: http://loki-spot.logging.svc.cluster.local:3100/loki/api/v1/push

        grafana:
          enabled: false

        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus-stack
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true