apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-spot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"    
spec:
  project: default
  destination:
    name: spot-friendly
    namespace: kube-system
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.11.0 
    helm:
      values: |
        args:
          - --kubelet-insecure-tls
          - --kubelet-preferred-address-types=InternalIP
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true