apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos-objstore-secret
  namespace: argocd
spec:
  project: default
  destination:
    name: spot-friendly
    namespace: monitoring
  source:
    repoURL: https://charts.helm.sh/incubator
    targetRevision: "0.2.5"
    chart: raw
    helm:
      values: |-
        resources:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: thanos-objstore-secret
              namespace: monitoring
            type: Opaque
            stringData:
              objstore.yaml: |
                type: S3
                config:
                  bucket: j1-lab-thanos
                  endpoint: s3.ap-northeast-2.amazonaws.com
                  region: ap-northeast-2
                  insecure: false                 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true